id: opecha:P000542
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ7445
  title: བཀའ་འགྱུར། ༼ལི་ཐང༽
  volume:
    04a88a7dc714433e86bd55903de6fc26:
      image_group_id: I1KG9868
      title: Volume 1 of bka' 'gyur/ (li thang /)
      volume_number: 1
      total_pages: 632
    7bb718eac0104494a0b91b88c395c79e:
      image_group_id: I1KG9869
      title: Volume 2 of bka' 'gyur/ (li thang /)
      volume_number: 2
      total_pages: 642
    d5f6e468aec04f69afb53f4b835c7d7d:
      image_group_id: I1KG9870
      title: Volume 3 of bka' 'gyur/ (li thang /)
      volume_number: 3
      total_pages: 632
    88c06c612b7a4d9a88ed70d739d70735:
      image_group_id: I1KG9871
      title: Volume 4 of bka' 'gyur/ (li thang /)
      volume_number: 4
      total_pages: 1228
    4c8be6943c314eaea0839e8b95b2427a:
      image_group_id: I1KG9872
      title: Volume 5 of bka' 'gyur/ (li thang /)
      volume_number: 5
      total_pages: 603
    57641cb74a404c779f0392c5121b2f56:
      image_group_id: I1KG9873
      title: Volume 6 of bka' 'gyur/ (li thang /)
      volume_number: 6
      total_pages: 569
    fc249617e8094915a918eef8077e8175:
      image_group_id: I1KG9874
      title: Volume 7 of bka' 'gyur/ (li thang /)
      volume_number: 7
      total_pages: 600
    0d47b5b2248243ddbedf8f0131b5f543:
      image_group_id: I1KG9875
      title: Volume 8 of bka' 'gyur/ (li thang /)
      volume_number: 8
      total_pages: 530
    c530de231ae14561b8dc38bec4bcc006:
      image_group_id: I1KG9876
      title: Volume 9 of bka' 'gyur/ (li thang /)
      volume_number: 9
      total_pages: 644
    db60bececfc343fb8ec8d47fd25c0263:
      image_group_id: I1KG9877
      title: Volume 10 of bka' 'gyur/ (li thang /)
      volume_number: 10
      total_pages: 662
    a137187ff5144a1aa36525f7475ee608:
      image_group_id: I1KG9878
      title: Volume 11 of bka' 'gyur/ (li thang /)
      volume_number: 11
      total_pages: 666
    ca60c45b7a014600a545b4fb2acb3ba9:
      image_group_id: I1KG9879
      title: Volume 12 of bka' 'gyur/ (li thang /)
      volume_number: 12
      total_pages: 596
    c4578343377943e4aa7aff1cf21f3995:
      image_group_id: I1KG9880
      title: Volume 13 of bka' 'gyur/ (li thang /)
      volume_number: 13
      total_pages: 696
    b426cb7d900047889e63cd8e3a4e3596:
      image_group_id: I1KG9881
      title: Volume 14 of bka' 'gyur/ (li thang /)
      volume_number: 14
      total_pages: 554
    8f055da5de7b4d7d8d79fbed06cb758b:
      image_group_id: I1KG9882
      title: Volume 15 of bka' 'gyur/ (li thang /)
      volume_number: 15
      total_pages: 552
    52965f97b32744419955e5775c423649:
      image_group_id: I1KG9883
      title: Volume 16 of bka' 'gyur/ (li thang /)
      volume_number: 16
      total_pages: 560
    33d86a5d3e2e4398869315d415c10491:
      image_group_id: I1KG9884
      title: Volume 17 of bka' 'gyur/ (li thang /)
      volume_number: 17
      total_pages: 562
    cc356ede0de441eebcb7ec20b4125ff2:
      image_group_id: I1KG9885
      title: Volume 18 of bka' 'gyur/ (li thang /)
      volume_number: 18
      total_pages: 626
    195d3f4ccc804f50b21a9d5910b97a5d:
      image_group_id: I1KG9886
      title: Volume 19 of bka' 'gyur/ (li thang /)
      volume_number: 19
      total_pages: 598
    855e93ae65524c4dbcfef54d1abf574f:
      image_group_id: I1KG9887
      title: Volume 20 of bka' 'gyur/ (li thang /)
      volume_number: 20
      total_pages: 602
    76efa8277d7c46418f6ff76df86aded9:
      image_group_id: I1KG9888
      title: Volume 21 of bka' 'gyur/ (li thang /)
      volume_number: 21
      total_pages: 586
    41abf831b84b4530b5f5b68c72835a7e:
      image_group_id: I1KG9889
      title: Volume 22 of bka' 'gyur/ (li thang /)
      volume_number: 22
      total_pages: 654
    93bd6300840747428353a306e9d3ad79:
      image_group_id: I1KG9890
      title: Volume 23 of bka' 'gyur/ (li thang /)
      volume_number: 23
      total_pages: 584
    d01e9c8cf9144e6e923277867a42635b:
      image_group_id: I1KG9891
      title: Volume 24 of bka' 'gyur/ (li thang /)
      volume_number: 24
      total_pages: 615
    38fdb758a78141f18959c3833a910492:
      image_group_id: I1KG9892
      title: Volume 25 of bka' 'gyur/ (li thang /)
      volume_number: 25
      total_pages: 636
    ba4079eb38c345dcb7132d8c6330ed73:
      image_group_id: I1KG9893
      title: Volume 26 of bka' 'gyur/ (li thang /)
      volume_number: 26
      total_pages: 632
    3c43149fc84d4f8ca1bec381a3820efd:
      image_group_id: I1KG9894
      title: Volume 27 of bka' 'gyur/ (li thang /)
      volume_number: 27
      total_pages: 616
    e8319229900b4cb0a59fafc78b19ca20:
      image_group_id: I1KG9895
      title: Volume 28 of bka' 'gyur/ (li thang /)
      volume_number: 28
      total_pages: 622
    2c7e171fb83843d1ba3c1ba6b6e6a5f6:
      image_group_id: I1KG9896
      title: Volume 29 of bka' 'gyur/ (li thang /)
      volume_number: 29
      total_pages: 624
    5f529654d17b4ab9bcbf3004e8f12400:
      image_group_id: I1KG9897
      title: Volume 30 of bka' 'gyur/ (li thang /)
      volume_number: 30
      total_pages: 630
    54b3ed602d95492f96dd22c5880b62dd:
      image_group_id: I1KG9898
      title: Volume 31 of bka' 'gyur/ (li thang /)
      volume_number: 31
      total_pages: 642
    366203a7684f408f86dcfc39deb4f034:
      image_group_id: I1KG9899
      title: Volume 32 of bka' 'gyur/ (li thang /)
      volume_number: 32
      total_pages: 608
    4dd6be6268f149148b2c9a41d1b4c0a6:
      image_group_id: I1KG9900
      title: Volume 33 of bka' 'gyur/ (li thang /)
      volume_number: 33
      total_pages: 618
    0ef5bac5346441beac04399918987e26:
      image_group_id: I1KG9901
      title: Volume 34 of bka' 'gyur/ (li thang /)
      volume_number: 34
      total_pages: 572
    649784d6c35349ad9d8928e8ee52a21d:
      image_group_id: I1KG9902
      title: Volume 35 of bka' 'gyur/ (li thang /)
      volume_number: 35
      total_pages: 588
    aed5cf9ad3f74a05896180c578ad6723:
      image_group_id: I1KG9903
      title: Volume 36 of bka' 'gyur/ (li thang /)
      volume_number: 36
      total_pages: 628
    d1edcd5d55c5493d9ba47757b196f1af:
      image_group_id: I1KG9904
      title: Volume 37 of bka' 'gyur/ (li thang /)
      volume_number: 37
      total_pages: 593
    03ff68d35d3d4c7381262720a14410f7:
      image_group_id: I1KG9905
      title: Volume 38 of bka' 'gyur/ (li thang /)
      volume_number: 38
      total_pages: 544
    f3db9f3b0da04b588f4b28bebfcad540:
      image_group_id: I1KG9906
      title: Volume 39 of bka' 'gyur/ (li thang /)
      volume_number: 39
      total_pages: 617
    4895da4002274920967672a77403a739:
      image_group_id: I1KG9907
      title: Volume 40 of bka' 'gyur/ (li thang /)
      volume_number: 40
      total_pages: 718
    761c0d0e80b7446dbe66f5c87b8dd23b:
      image_group_id: I1KG9908
      title: Volume 41 of bka' 'gyur/ (li thang /)
      volume_number: 41
      total_pages: 624
    3480169f167445a99ba188bd96737113:
      image_group_id: I1KG9909
      title: Volume 42 of bka' 'gyur/ (li thang /)
      volume_number: 42
      total_pages: 651
    0137cf0b711f47d3b66521520eba0e02:
      image_group_id: I1KG9910
      title: Volume 43 of bka' 'gyur/ (li thang /)
      volume_number: 43
      total_pages: 608
    69f4cc9da77a475d92b3a976c604fa19:
      image_group_id: I1KG9911
      title: Volume 44 of bka' 'gyur/ (li thang /)
      volume_number: 44
      total_pages: 628
    6707707c40fe4fc3ab748bb71a6fe9ac:
      image_group_id: I1KG9912
      title: Volume 45 of bka' 'gyur/ (li thang /)
      volume_number: 45
      total_pages: 628
    4a4c8e8203ce4d8eb9baae53bac1a183:
      image_group_id: I1KG9913
      title: Volume 46 of bka' 'gyur/ (li thang /)
      volume_number: 46
      total_pages: 634
    a80faac211914b32b95443aa5e3d7f51:
      image_group_id: I1KG9914
      title: Volume 47 of bka' 'gyur/ (li thang /)
      volume_number: 47
      total_pages: 722
    a7dc5deb774d4e618914a998549c1293:
      image_group_id: I1KG9915
      title: Volume 48 of bka' 'gyur/ (li thang /)
      volume_number: 48
      total_pages: 666
    5be25d725208497b9edf32839c6c68ac:
      image_group_id: I1KG9916
      title: Volume 49 of bka' 'gyur/ (li thang /)
      volume_number: 49
      total_pages: 568
    630158558368491cb2572b306b904520:
      image_group_id: I1KG9917
      title: Volume 50 of bka' 'gyur/ (li thang /)
      volume_number: 50
      total_pages: 666
    12362bea09ef4f11bfa09bdd572dd2a4:
      image_group_id: I1KG9918
      title: Volume 51 of bka' 'gyur/ (li thang /)
      volume_number: 51
      total_pages: 644
    ee284ce7bd3c4efb912522ca9bb80eef:
      image_group_id: I1KG9919
      title: Volume 52 of bka' 'gyur/ (li thang /)
      volume_number: 52
      total_pages: 586
    9168cbc9e93646b789e3d18fbe362570:
      image_group_id: I1KG9920
      title: Volume 53 of bka' 'gyur/ (li thang /)
      volume_number: 53
      total_pages: 722
    b779d20c88d94b059b086dca58be21ca:
      image_group_id: I1KG9921
      title: Volume 54 of bka' 'gyur/ (li thang /)
      volume_number: 54
      total_pages: 628
    e61ac46a2e154250bea0cbfdcd2b218d:
      image_group_id: I1KG9922
      title: Volume 55 of bka' 'gyur/ (li thang /)
      volume_number: 55
      total_pages: 652
    292327f124be494a8cbd40e4d5e2c58b:
      image_group_id: I1KG9923
      title: Volume 56 of bka' 'gyur/ (li thang /)
      volume_number: 56
      total_pages: 676
    2f33abfd686a4cb7a911b4ec2d0ed964:
      image_group_id: I1KG9924
      title: Volume 57 of bka' 'gyur/ (li thang /)
      volume_number: 57
      total_pages: 680
    047b74128000489981393c1414d918b0:
      image_group_id: I1KG9925
      title: Volume 58 of bka' 'gyur/ (li thang /)
      volume_number: 58
      total_pages: 664
    f89de1c5913648d3bbfbd6961a5d0c64:
      image_group_id: I1KG9926
      title: Volume 59 of bka' 'gyur/ (li thang /)
      volume_number: 59
      total_pages: 712
    55b3aaa4a49d434581d1e9c9f9b2c37c:
      image_group_id: I1KG9927
      title: Volume 60 of bka' 'gyur/ (li thang /)
      volume_number: 60
      total_pages: 674
    382ce38e145e439dbe65f2b7092e6e14:
      image_group_id: I1KG9928
      title: Volume 61 of bka' 'gyur/ (li thang /)
      volume_number: 61
      total_pages: 666
    e4a4e7fea07a413baab8229466a75a41:
      image_group_id: I1KG9929
      title: Volume 62 of bka' 'gyur/ (li thang /)
      volume_number: 62
      total_pages: 688
    cfc66ce0fc4447799699f9740951917b:
      image_group_id: I1KG9930
      title: Volume 63 of bka' 'gyur/ (li thang /)
      volume_number: 63
      total_pages: 666
    207660b46e314c42b47b0444fe301e6d:
      image_group_id: I1KG9931
      title: Volume 64 of bka' 'gyur/ (li thang /)
      volume_number: 64
      total_pages: 664
    61c8433c12c949239712d2e383dcc7df:
      image_group_id: I1KG9932
      title: Volume 65 of bka' 'gyur/ (li thang /)
      volume_number: 65
      total_pages: 690
    305fb356a961488ea1b2012aefb8be90:
      image_group_id: I1KG9933
      title: Volume 66 of bka' 'gyur/ (li thang /)
      volume_number: 66
      total_pages: 676
    a2ed617b41c14881a439b7e424decbcf:
      image_group_id: I1KG9934
      title: Volume 67 of bka' 'gyur/ (li thang /)
      volume_number: 67
      total_pages: 658
    ce5ccb1d4d0b4e68aee0c38469cbdfca:
      image_group_id: I1KG9935
      title: Volume 68 of bka' 'gyur/ (li thang /)
      volume_number: 68
      total_pages: 664
    b6b567da64bf4cd1a5a09979e4008d02:
      image_group_id: I1KG9936
      title: Volume 69 of bka' 'gyur/ (li thang /)
      volume_number: 69
      total_pages: 3
    d587bd2d09c844ccb990507d22586ee3:
      image_group_id: I1KG9937
      title: Volume 70 of bka' 'gyur/ (li thang /)
      volume_number: 70
      total_pages: 648
    1d763795f6374e3c95650683c286f848:
      image_group_id: I1KG9938
      title: Volume 71 of bka' 'gyur/ (li thang /)
      volume_number: 71
      total_pages: 596
    4e069f71c7ad4c828610f8be5708b223:
      image_group_id: I1KG9939
      title: Volume 72 of bka' 'gyur/ (li thang /)
      volume_number: 72
      total_pages: 3
    9c7ded9ee4c146b987104725c60cee93:
      image_group_id: I1KG9940
      title: Volume 73 of bka' 'gyur/ (li thang /)
      volume_number: 73
      total_pages: 475
    3324d7105e9b4344ac95d7d9c5da577d:
      image_group_id: I1KG9941
      title: Volume 74 of bka' 'gyur/ (li thang /)
      volume_number: 74
      total_pages: 606
    5fd12fb3506b4e2e9f79e719de7778cd:
      image_group_id: I1KG9942
      title: Volume 75 of bka' 'gyur/ (li thang /)
      volume_number: 75
      total_pages: 516
    910903ea8acb4788883735aa8600ce7f:
      image_group_id: I1KG9943
      title: Volume 76 of bka' 'gyur/ (li thang /)
      volume_number: 76
      total_pages: 594
    826e1686cb24483ba2688a4ba5da8f15:
      image_group_id: I1KG9944
      title: Volume 77 of bka' 'gyur/ (li thang /)
      volume_number: 77
      total_pages: 564
    7f1deac893ec41d9bf222e3b82256607:
      image_group_id: I1KG9945
      title: Volume 78 of bka' 'gyur/ (li thang /)
      volume_number: 78
      total_pages: 634
    ba5cf7cbb3e74051b219bb8c187fc6a0:
      image_group_id: I1KG9946
      title: Volume 79 of bka' 'gyur/ (li thang /)
      volume_number: 79
      total_pages: 682
    e93505f1cd324758b5f4203497eba7a5:
      image_group_id: I1KG9947
      title: Volume 80 of bka' 'gyur/ (li thang /)
      volume_number: 80
      total_pages: 716
    4000a40755ab4b65bb768246d9602e10:
      image_group_id: I1KG9948
      title: Volume 81 of bka' 'gyur/ (li thang /)
      volume_number: 81
      total_pages: 656
    1a8316a82142493883d96ba697c70968:
      image_group_id: I1KG9949
      title: Volume 82 of bka' 'gyur/ (li thang /)
      volume_number: 82
      total_pages: 704
    d9e4b50aa9d04a409e6bd843521cfe5e:
      image_group_id: I1KG9950
      title: Volume 83 of bka' 'gyur/ (li thang /)
      volume_number: 83
      total_pages: 656
    a36c734d3a2f4f849283897bd86e191d:
      image_group_id: I1KG9951
      title: Volume 84 of bka' 'gyur/ (li thang /)
      volume_number: 84
      total_pages: 670
    74621929eb994c9c8914d349210905e6:
      image_group_id: I1KG9952
      title: Volume 85 of bka' 'gyur/ (li thang /)
      volume_number: 85
      total_pages: 710
    cbbbaa8632e248cb8037b01a041a1286:
      image_group_id: I1KG9953
      title: Volume 86 of bka' 'gyur/ (li thang /)
      volume_number: 86
      total_pages: 774
    e65d493842914b78800d26551b28d7ac:
      image_group_id: I1KG9954
      title: Volume 87 of bka' 'gyur/ (li thang /)
      volume_number: 87
      total_pages: 656
    cdd4c681e297457d97e3199d0dac824f:
      image_group_id: I1KG9955
      title: Volume 88 of bka' 'gyur/ (li thang /)
      volume_number: 88
      total_pages: 750
    965396067df54850aee4523928a3f0a3:
      image_group_id: I1KG9956
      title: Volume 89 of bka' 'gyur/ (li thang /)
      volume_number: 89
      total_pages: 654
    feb8e021185c45a4a27765a479a1b06f:
      image_group_id: I1KG9957
      title: Volume 90 of bka' 'gyur/ (li thang /)
      volume_number: 90
      total_pages: 506
    7ab175b12c2242928c5da13db4b29008:
      image_group_id: I1KG9958
      title: Volume 91 of bka' 'gyur/ (li thang /)
      volume_number: 91
      total_pages: 3
    ae1bdb64d3984229b3ecf03b623a9174:
      image_group_id: I1KG9959
      title: Volume 92 of bka' 'gyur/ (li thang /)
      volume_number: 92
      total_pages: 670
    d07cdc00e67a4261b8a6958e50d98a75:
      image_group_id: I1KG9960
      title: Volume 93 of bka' 'gyur/ (li thang /)
      volume_number: 93
      total_pages: 621
    1a24459077074cc68bf4242b79ad1034:
      image_group_id: I1KG9961
      title: Volume 94 of bka' 'gyur/ (li thang /)
      volume_number: 94
      total_pages: 614
    2df762d184dd46cebcce645ebf138b25:
      image_group_id: I1KG9962
      title: Volume 95 of bka' 'gyur/ (li thang /)
      volume_number: 95
      total_pages: 612
    32395852f12e4f5483e3c4df0d8332a6:
      image_group_id: I1KG9963
      title: Volume 96 of bka' 'gyur/ (li thang /)
      volume_number: 96
      total_pages: 602
    4f8010399b6b4f4dbed7ff2572053e13:
      image_group_id: I1KG9964
      title: Volume 97 of bka' 'gyur/ (li thang /)
      volume_number: 97
      total_pages: 644
    5c31901b233f4154b13d9ce860ce529e:
      image_group_id: I1KG9965
      title: Volume 98 of bka' 'gyur/ (li thang /)
      volume_number: 98
      total_pages: 640
    a7331cf3814843519ace3905dbee5eba:
      image_group_id: I1KG9966
      title: Volume 99 of bka' 'gyur/ (li thang /)
      volume_number: 99
      total_pages: 656
    b2bdbce66fa4408b8df909c99aca9b27:
      image_group_id: I1KG9967
      title: Volume 100 of bka' 'gyur/ (li thang /)
      volume_number: 100
      total_pages: 3
    f2a77eeb137e44b4b078b92589140055:
      image_group_id: I1KG9968
      title: Volume 101 of bka' 'gyur/ (li thang /)
      volume_number: 101
      total_pages: 690
    9cef6255a2604dc08b322d4ec5b8136e:
      image_group_id: I1KG9969
      title: Volume 102 of bka' 'gyur/ (li thang /)
      volume_number: 102
      total_pages: 696
    5e3a907a2f764ed9ae7d2a9a6fc7c902:
      image_group_id: I1KG9970
      title: Volume 103 of bka' 'gyur/ (li thang /)
      volume_number: 103
      total_pages: 616
    7b820dfdd1644576835b26561a94ec88:
      image_group_id: I1KG9971
      title: Volume 104 of bka' 'gyur/ (li thang /)
      volume_number: 104
      total_pages: 534
    b61a6131fdff4df0a4b54b8304accf3a:
      image_group_id: I1KG9972
      title: Volume 105 of bka' 'gyur/ (li thang /)
      volume_number: 105
      total_pages: 610
    ee111d83fb3d442bb4e4ebc563182225:
      image_group_id: I1KG9973
      title: Volume 106 of bka' 'gyur/ (li thang /)
      volume_number: 106
      total_pages: 554
    c351f70de4ec4f8cae29aa82a8ee0bc5:
      image_group_id: I1KG9974
      title: Volume 107 of bka' 'gyur/ (li thang /)
      volume_number: 107
      total_pages: 505
    d27f17645bfb41769a3a544b9420b6e6:
      image_group_id: I1KG9975
      title: Volume 108 of bka' 'gyur/ (li thang /)
      volume_number: 108
      total_pages: 449
    39181b7bbe6749d498c612619d15eaf9:
      image_group_id: I1KG9976
      title: Volume 109 of bka' 'gyur/ (li thang /)
      volume_number: 109
      total_pages: 139
  author: ''
ebook_metadata:
  title: བཀའ་འགྱུར། ༼ལི་ཐང༽
  author: ''
  sku: P000542
  cover: cover.jpg
  layers:
  - pagination
