id: I0673ACC7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T00:05:36+00:00'
last_modified: '2022-06-16T04:43:30.938503+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ7445
  title: བཀའ་འགྱུར། ༼ལི་ཐང༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B4C7:
      image_group_id: I1KG9868
      title: Volume 1 of bka' 'gyur/ (li thang /)
      total_pages: 632
      order: 1
      base_file: B4C7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
